"""initial schema

Revision ID: c6a23e8ca55e
Revises: 
Create Date: 2026-03-24 14:47:18.940874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6a23e8ca55e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estadios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacidade', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['nome'])

    with op.batch_alter_table('jogadores', schema=None) as batch_op:
        batch_op.alter_column('time_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('partidas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_casa_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('time_fora_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('estadio_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'times', ['time_casa_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'estadios', ['estadio_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'times', ['time_fora_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('time_fora')
        batch_op.drop_column('time_casa')

    with op.batch_alter_table('times', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nome'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('times', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('partidas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_casa', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('time_fora', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('estadio_id')
        batch_op.drop_column('time_fora_id')
        batch_op.drop_column('time_casa_id')

    with op.batch_alter_table('jogadores', schema=None) as batch_op:
        batch_op.alter_column('time_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('estadios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('capacidade')

    # ### end Alembic commands ###
